
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teqcisbknphktkhliiwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlcWNpc2JrbnBoa3RraGxpaXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzMxMDksImV4cCI6MjA1ODY0OTEwOX0.rAEK8KnhsYid9mDskiY5_pLA-vq-YLetf6EvHKQvI-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
    },
    db: {
      schema: 'public',
    },
  }
);
